development:
  adapter: postgresql
  encoding: utf8
  database: devinsanta_development
  pool: 5
  username: devinsanta
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: devinsanta_test
  pool: 5
  username: devinsanta
  min_messages: WARNING
  host: localhost
  template: template0
